const actionTypes = {
  SET_ALL_COUNTRIES: "SET_ALL_COUNTRIES",
  SET_DAILY_DATA: "SET_DAILY_DATA",
  SET_COUNTRY_DATA: "SET_COUNTRY_DATA_ACTION",
  SET_CURRENT_COUNTRY: "SET_CURRENT_COUNTRY",
  SET_OVERALL_DATA: "SET_OVERALL_DATA",
};

export default actionTypes;
